version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    #network_mode: host
    volumes:
      - ./src:/etc/nginx/conf.d
      - ./src:/var/www/html/
